// PROPERTY ACTIONS
export const GET_PROPERTIES = "GET_PROPERTIES";
export const PROPERTY_LOADING = "PROPERTY_LOADING";
export const CREATE_PROPERTY = "CREATE_PROPERTY";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
export const GET_PROPERTY = "GET_PROPERTY";
